
package com.View;

/**
 * @author Miguel Rdz
 * @since 16/07/2013
 * @version 1.0
 */
public class Keyboardx extends javax.swing.JFrame {
    
    private String output;
    private boolean caps;  
    private boolean isPassword;
    
    /**
     * Creates new form Keyboard
     */
    public Keyboardx(String title, boolean isPass) {
        this.caps = false;
        this.setTitle(title);
        this.isPassword = isPass;
        this.output = "";
        this.setResizable(false);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_keys = new javax.swing.JPanel();
        btn_q = new javax.swing.JButton();
        btn_w = new javax.swing.JButton();
        btn_e = new javax.swing.JButton();
        btn_r = new javax.swing.JButton();
        btn_t = new javax.swing.JButton();
        btn_y = new javax.swing.JButton();
        btn_u = new javax.swing.JButton();
        btn_p = new javax.swing.JButton();
        btn_i = new javax.swing.JButton();
        btn_o = new javax.swing.JButton();
        btn_a = new javax.swing.JButton();
        btn_s = new javax.swing.JButton();
        btn_d = new javax.swing.JButton();
        btn_f = new javax.swing.JButton();
        btn_g = new javax.swing.JButton();
        btn_h = new javax.swing.JButton();
        btn_j = new javax.swing.JButton();
        btn_k = new javax.swing.JButton();
        btn_l = new javax.swing.JButton();
        btn_z = new javax.swing.JButton();
        btn_x = new javax.swing.JButton();
        btn_c = new javax.swing.JButton();
        btn_v = new javax.swing.JButton();
        btn_b = new javax.swing.JButton();
        btn_n = new javax.swing.JButton();
        btn_m = new javax.swing.JButton();
        btn_under = new javax.swing.JButton();
        btn_dot = new javax.swing.JButton();
        btn_caps = new javax.swing.JButton();
        btn_num = new javax.swing.JButton();
        btn_space = new javax.swing.JButton();
        btn_bckspace = new javax.swing.JButton();
        btn_ok = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();
        txf_keyOutput = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setAlwaysOnTop(true);

        btn_q.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn_q.setText("q");
        btn_q.setBorderPainted(false);
        btn_q.setFocusPainted(false);
        btn_q.setFocusable(false);
        btn_q.setMaximumSize(new java.awt.Dimension(60, 60));
        btn_q.setMinimumSize(new java.awt.Dimension(60, 60));
        btn_q.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_qActionPerformed(evt);
            }
        });

        btn_w.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn_w.setText("w");
        btn_w.setBorderPainted(false);
        btn_w.setFocusPainted(false);
        btn_w.setFocusable(false);
        btn_w.setMaximumSize(new java.awt.Dimension(60, 60));
        btn_w.setMinimumSize(new java.awt.Dimension(60, 60));
        btn_w.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_wActionPerformed(evt);
            }
        });

        btn_e.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn_e.setText("e");
        btn_e.setBorderPainted(false);
        btn_e.setFocusPainted(false);
        btn_e.setFocusable(false);
        btn_e.setMaximumSize(new java.awt.Dimension(60, 60));
        btn_e.setMinimumSize(new java.awt.Dimension(60, 60));
        btn_e.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eActionPerformed(evt);
            }
        });

        btn_r.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn_r.setText("r");
        btn_r.setBorderPainted(false);
        btn_r.setFocusPainted(false);
        btn_r.setFocusable(false);
        btn_r.setMaximumSize(new java.awt.Dimension(60, 60));
        btn_r.setMinimumSize(new java.awt.Dimension(60, 60));
        btn_r.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rActionPerformed(evt);
            }
        });

        btn_t.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn_t.setText("t");
        btn_t.setBorderPainted(false);
        btn_t.setFocusPainted(false);
        btn_t.setFocusable(false);
        btn_t.setMaximumSize(new java.awt.Dimension(60, 60));
        btn_t.setMinimumSize(new java.awt.Dimension(60, 60));
        btn_t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tActionPerformed(evt);
            }
        });

        btn_y.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn_y.setText("y");
        btn_y.setBorderPainted(false);
        btn_y.setFocusPainted(false);
        btn_y.setFocusable(false);
        btn_y.setMaximumSize(new java.awt.Dimension(60, 60));
        btn_y.setMinimumSize(new java.awt.Dimension(60, 60));
        btn_y.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_yActionPerformed(evt);
            }
        });

        btn_u.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn_u.setText("u");
        btn_u.setBorderPainted(false);
        btn_u.setFocusPainted(false);
        btn_u.setFocusable(false);
        btn_u.setMaximumSize(new java.awt.Dimension(60, 60));
        btn_u.setMinimumSize(new java.awt.Dimension(60, 60));
        btn_u.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_uActionPerformed(evt);
            }
        });

        btn_p.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn_p.setText("p");
        btn_p.setBorderPainted(false);
        btn_p.setFocusPainted(false);
        btn_p.setFocusable(false);
        btn_p.setMaximumSize(new java.awt.Dimension(60, 60));
        btn_p.setMinimumSize(new java.awt.Dimension(60, 60));
        btn_p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pActionPerformed(evt);
            }
        });

        btn_i.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn_i.setText("i");
        btn_i.setBorderPainted(false);
        btn_i.setFocusPainted(false);
        btn_i.setFocusable(false);
        btn_i.setMaximumSize(new java.awt.Dimension(60, 60));
        btn_i.setMinimumSize(new java.awt.Dimension(60, 60));
        btn_i.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_iActionPerformed(evt);
            }
        });

        btn_o.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn_o.setText("o");
        btn_o.setBorderPainted(false);
        btn_o.setFocusPainted(false);
        btn_o.setFocusable(false);
        btn_o.setMaximumSize(new java.awt.Dimension(60, 60));
        btn_o.setMinimumSize(new java.awt.Dimension(60, 60));
        btn_o.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_oActionPerformed(evt);
            }
        });

        btn_a.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn_a.setText("a");
        btn_a.setBorderPainted(false);
        btn_a.setFocusPainted(false);
        btn_a.setFocusable(false);
        btn_a.setMaximumSize(new java.awt.Dimension(60, 60));
        btn_a.setMinimumSize(new java.awt.Dimension(60, 60));
        btn_a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aActionPerformed(evt);
            }
        });

        btn_s.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn_s.setText("s");
        btn_s.setBorderPainted(false);
        btn_s.setFocusPainted(false);
        btn_s.setFocusable(false);
        btn_s.setMaximumSize(new java.awt.Dimension(60, 60));
        btn_s.setMinimumSize(new java.awt.Dimension(60, 60));
        btn_s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sActionPerformed(evt);
            }
        });

        btn_d.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn_d.setText("d");
        btn_d.setBorderPainted(false);
        btn_d.setFocusPainted(false);
        btn_d.setFocusable(false);
        btn_d.setMaximumSize(new java.awt.Dimension(60, 60));
        btn_d.setMinimumSize(new java.awt.Dimension(60, 60));
        btn_d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dActionPerformed(evt);
            }
        });

        btn_f.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn_f.setText("f");
        btn_f.setBorderPainted(false);
        btn_f.setFocusPainted(false);
        btn_f.setFocusable(false);
        btn_f.setMaximumSize(new java.awt.Dimension(60, 60));
        btn_f.setMinimumSize(new java.awt.Dimension(60, 60));
        btn_f.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fActionPerformed(evt);
            }
        });

        btn_g.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn_g.setText("g");
        btn_g.setBorderPainted(false);
        btn_g.setFocusPainted(false);
        btn_g.setFocusable(false);
        btn_g.setMaximumSize(new java.awt.Dimension(60, 60));
        btn_g.setMinimumSize(new java.awt.Dimension(60, 60));
        btn_g.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gActionPerformed(evt);
            }
        });

        btn_h.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn_h.setText("h");
        btn_h.setBorderPainted(false);
        btn_h.setFocusPainted(false);
        btn_h.setFocusable(false);
        btn_h.setMaximumSize(new java.awt.Dimension(60, 60));
        btn_h.setMinimumSize(new java.awt.Dimension(60, 60));
        btn_h.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hActionPerformed(evt);
            }
        });

        btn_j.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn_j.setText("j");
        btn_j.setBorderPainted(false);
        btn_j.setFocusPainted(false);
        btn_j.setFocusable(false);
        btn_j.setMaximumSize(new java.awt.Dimension(60, 60));
        btn_j.setMinimumSize(new java.awt.Dimension(60, 60));
        btn_j.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_jActionPerformed(evt);
            }
        });

        btn_k.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn_k.setText("k");
        btn_k.setBorderPainted(false);
        btn_k.setFocusPainted(false);
        btn_k.setFocusable(false);
        btn_k.setMaximumSize(new java.awt.Dimension(60, 60));
        btn_k.setMinimumSize(new java.awt.Dimension(60, 60));
        btn_k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kActionPerformed(evt);
            }
        });

        btn_l.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn_l.setText("l");
        btn_l.setBorderPainted(false);
        btn_l.setFocusPainted(false);
        btn_l.setFocusable(false);
        btn_l.setMaximumSize(new java.awt.Dimension(60, 60));
        btn_l.setMinimumSize(new java.awt.Dimension(60, 60));
        btn_l.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lActionPerformed(evt);
            }
        });

        btn_z.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn_z.setText("z");
        btn_z.setBorderPainted(false);
        btn_z.setFocusPainted(false);
        btn_z.setFocusable(false);
        btn_z.setMaximumSize(new java.awt.Dimension(60, 60));
        btn_z.setMinimumSize(new java.awt.Dimension(60, 60));
        btn_z.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_zActionPerformed(evt);
            }
        });

        btn_x.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn_x.setText("x");
        btn_x.setBorderPainted(false);
        btn_x.setFocusPainted(false);
        btn_x.setFocusable(false);
        btn_x.setMaximumSize(new java.awt.Dimension(60, 60));
        btn_x.setMinimumSize(new java.awt.Dimension(60, 60));
        btn_x.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xActionPerformed(evt);
            }
        });

        btn_c.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn_c.setText("c");
        btn_c.setBorderPainted(false);
        btn_c.setFocusPainted(false);
        btn_c.setFocusable(false);
        btn_c.setMaximumSize(new java.awt.Dimension(60, 60));
        btn_c.setMinimumSize(new java.awt.Dimension(60, 60));
        btn_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cActionPerformed(evt);
            }
        });

        btn_v.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn_v.setText("v");
        btn_v.setBorderPainted(false);
        btn_v.setFocusPainted(false);
        btn_v.setFocusable(false);
        btn_v.setMaximumSize(new java.awt.Dimension(60, 60));
        btn_v.setMinimumSize(new java.awt.Dimension(60, 60));
        btn_v.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_vActionPerformed(evt);
            }
        });

        btn_b.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn_b.setText("b");
        btn_b.setBorderPainted(false);
        btn_b.setFocusPainted(false);
        btn_b.setFocusable(false);
        btn_b.setMaximumSize(new java.awt.Dimension(60, 60));
        btn_b.setMinimumSize(new java.awt.Dimension(60, 60));
        btn_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bActionPerformed(evt);
            }
        });

        btn_n.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn_n.setText("n");
        btn_n.setBorderPainted(false);
        btn_n.setFocusPainted(false);
        btn_n.setFocusable(false);
        btn_n.setMaximumSize(new java.awt.Dimension(60, 60));
        btn_n.setMinimumSize(new java.awt.Dimension(60, 60));
        btn_n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nActionPerformed(evt);
            }
        });

        btn_m.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn_m.setText("m");
        btn_m.setBorderPainted(false);
        btn_m.setFocusPainted(false);
        btn_m.setFocusable(false);
        btn_m.setMaximumSize(new java.awt.Dimension(60, 60));
        btn_m.setMinimumSize(new java.awt.Dimension(60, 60));
        btn_m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mActionPerformed(evt);
            }
        });

        btn_under.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn_under.setText("_");
        btn_under.setBorderPainted(false);
        btn_under.setFocusPainted(false);
        btn_under.setFocusable(false);
        btn_under.setMaximumSize(new java.awt.Dimension(60, 60));
        btn_under.setMinimumSize(new java.awt.Dimension(60, 60));
        btn_under.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_underActionPerformed(evt);
            }
        });

        btn_dot.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn_dot.setText(".");
        btn_dot.setBorderPainted(false);
        btn_dot.setFocusPainted(false);
        btn_dot.setFocusable(false);
        btn_dot.setMaximumSize(new java.awt.Dimension(60, 60));
        btn_dot.setMinimumSize(new java.awt.Dimension(60, 60));
        btn_dot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dotActionPerformed(evt);
            }
        });

        btn_caps.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn_caps.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/caps.png"))); // NOI18N
        btn_caps.setBorderPainted(false);
        btn_caps.setFocusPainted(false);
        btn_caps.setFocusable(false);
        btn_caps.setMaximumSize(new java.awt.Dimension(60, 60));
        btn_caps.setMinimumSize(new java.awt.Dimension(60, 60));
        btn_caps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_capsActionPerformed(evt);
            }
        });

        btn_num.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn_num.setText("123...");
        btn_num.setBorderPainted(false);
        btn_num.setFocusPainted(false);
        btn_num.setFocusable(false);
        btn_num.setMaximumSize(new java.awt.Dimension(60, 60));
        btn_num.setMinimumSize(new java.awt.Dimension(60, 60));

        btn_space.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn_space.setBorderPainted(false);
        btn_space.setFocusPainted(false);
        btn_space.setFocusable(false);
        btn_space.setMaximumSize(new java.awt.Dimension(60, 60));
        btn_space.setMinimumSize(new java.awt.Dimension(60, 60));
        btn_space.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_spaceActionPerformed(evt);
            }
        });

        btn_bckspace.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn_bckspace.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/backspace.png"))); // NOI18N
        btn_bckspace.setBorderPainted(false);
        btn_bckspace.setFocusPainted(false);
        btn_bckspace.setFocusable(false);
        btn_bckspace.setMaximumSize(new java.awt.Dimension(60, 60));
        btn_bckspace.setMinimumSize(new java.awt.Dimension(60, 60));
        btn_bckspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bckspaceActionPerformed(evt);
            }
        });

        btn_ok.setBackground(new java.awt.Color(0, 153, 51));
        btn_ok.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn_ok.setText("Aceptar");
        btn_ok.setBorderPainted(false);
        btn_ok.setFocusPainted(false);
        btn_ok.setFocusable(false);
        btn_ok.setMaximumSize(new java.awt.Dimension(60, 60));
        btn_ok.setMinimumSize(new java.awt.Dimension(60, 60));
        btn_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_okActionPerformed(evt);
            }
        });

        btn_clear.setBackground(new java.awt.Color(153, 0, 0));
        btn_clear.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn_clear.setText("Borrar");
        btn_clear.setBorderPainted(false);
        btn_clear.setFocusPainted(false);
        btn_clear.setFocusable(false);
        btn_clear.setMaximumSize(new java.awt.Dimension(60, 60));
        btn_clear.setMinimumSize(new java.awt.Dimension(60, 60));
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        btn_cancel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn_cancel.setText("Cancelar");
        btn_cancel.setBorderPainted(false);
        btn_cancel.setFocusPainted(false);
        btn_cancel.setFocusable(false);
        btn_cancel.setMaximumSize(new java.awt.Dimension(60, 60));
        btn_cancel.setMinimumSize(new java.awt.Dimension(60, 60));
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_keysLayout = new javax.swing.GroupLayout(pnl_keys);
        pnl_keys.setLayout(pnl_keysLayout);
        pnl_keysLayout.setHorizontalGroup(
            pnl_keysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_keysLayout.createSequentialGroup()
                .addGroup(pnl_keysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_keysLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnl_keysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(pnl_keysLayout.createSequentialGroup()
                                .addComponent(btn_caps, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_z, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btn_num, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_keysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnl_keysLayout.createSequentialGroup()
                                .addComponent(btn_x, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_c, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_v, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_b, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_n, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_m, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_under, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btn_space, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_keysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_keysLayout.createSequentialGroup()
                                .addComponent(btn_dot, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(btn_cancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnl_keysLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_q, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_w, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_e, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_r, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_t, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_y, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_u, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_i, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_o, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_p, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_keysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_bckspace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_clear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)))
                    .addGroup(pnl_keysLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btn_a, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_s, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_d, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_f, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_g, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_h, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_j, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_k, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_l, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_ok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnl_keysLayout.setVerticalGroup(
            pnl_keysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_keysLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_keysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_q, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_w, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_e, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_r, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_t, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_y, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_u, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_i, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_o, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_p, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_bckspace, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_keysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnl_keysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_a, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_s, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_d, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_f, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_g, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_h, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_j, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_k, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_l, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_keysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnl_keysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_z, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_x, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_c, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_v, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_b, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_n, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_m, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_under, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_dot, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_caps, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_keysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_keysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_num, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_space, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txf_keyOutput.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnl_keys, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txf_keyOutput))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txf_keyOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(pnl_keys, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(858, 423));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kActionPerformed
        output += btn_k.getText();
        if (isPassword)
        {
            txf_keyOutput.setText(txf_keyOutput.getText().concat("*"));
        }
        else{
            txf_keyOutput.setText(output);
        }
    }//GEN-LAST:event_btn_kActionPerformed

    private void btn_jActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_jActionPerformed
        output = txf_keyOutput.getText().concat(btn_k.getText());
        txf_keyOutput.setText(txf_keyOutput.getText().concat(btn_j.getText()));
    }//GEN-LAST:event_btn_jActionPerformed

    private void btn_lActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lActionPerformed
        txf_keyOutput.setText(txf_keyOutput.getText().concat(btn_l.getText()));
    }//GEN-LAST:event_btn_lActionPerformed

    private void btn_qActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_qActionPerformed
        txf_keyOutput.setText(txf_keyOutput.getText().concat(btn_q.getText()));
    }//GEN-LAST:event_btn_qActionPerformed

    private void btn_wActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_wActionPerformed
        txf_keyOutput.setText(txf_keyOutput.getText().concat(btn_w.getText()));
    }//GEN-LAST:event_btn_wActionPerformed

    private void btn_eActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eActionPerformed
        txf_keyOutput.setText(txf_keyOutput.getText().concat(btn_e.getText()));
    }//GEN-LAST:event_btn_eActionPerformed

    private void btn_rActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rActionPerformed
        txf_keyOutput.setText(txf_keyOutput.getText().concat(btn_r.getText()));
    }//GEN-LAST:event_btn_rActionPerformed

    private void btn_tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tActionPerformed
        txf_keyOutput.setText(txf_keyOutput.getText().concat(btn_t.getText()));
    }//GEN-LAST:event_btn_tActionPerformed

    private void btn_yActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_yActionPerformed
        txf_keyOutput.setText(txf_keyOutput.getText().concat(btn_y.getText()));
    }//GEN-LAST:event_btn_yActionPerformed

    private void btn_uActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_uActionPerformed
        txf_keyOutput.setText(txf_keyOutput.getText().concat(btn_u.getText()));
    }//GEN-LAST:event_btn_uActionPerformed

    private void btn_iActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_iActionPerformed
        txf_keyOutput.setText(txf_keyOutput.getText().concat(btn_i.getText()));
    }//GEN-LAST:event_btn_iActionPerformed

    private void btn_oActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_oActionPerformed
        txf_keyOutput.setText(txf_keyOutput.getText().concat(btn_o.getText()));
    }//GEN-LAST:event_btn_oActionPerformed

    private void btn_pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pActionPerformed
        txf_keyOutput.setText(txf_keyOutput.getText().concat(btn_p.getText()));
    }//GEN-LAST:event_btn_pActionPerformed

    private void btn_aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aActionPerformed
        txf_keyOutput.setText(txf_keyOutput.getText().concat(btn_a.getText()));
    }//GEN-LAST:event_btn_aActionPerformed

    private void btn_sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sActionPerformed
        txf_keyOutput.setText(txf_keyOutput.getText().concat(btn_s.getText()));
    }//GEN-LAST:event_btn_sActionPerformed

    private void btn_dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dActionPerformed
        txf_keyOutput.setText(txf_keyOutput.getText().concat(btn_d.getText()));
    }//GEN-LAST:event_btn_dActionPerformed

    private void btn_fActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fActionPerformed
        txf_keyOutput.setText(txf_keyOutput.getText().concat(btn_f.getText()));
    }//GEN-LAST:event_btn_fActionPerformed

    private void btn_gActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gActionPerformed
        txf_keyOutput.setText(txf_keyOutput.getText().concat(btn_g.getText()));
    }//GEN-LAST:event_btn_gActionPerformed

    private void btn_hActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hActionPerformed
        txf_keyOutput.setText(txf_keyOutput.getText().concat(btn_h.getText()));
    }//GEN-LAST:event_btn_hActionPerformed

    private void btn_zActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_zActionPerformed
        txf_keyOutput.setText(txf_keyOutput.getText().concat(btn_z.getText()));
    }//GEN-LAST:event_btn_zActionPerformed

    private void btn_xActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xActionPerformed
        txf_keyOutput.setText(txf_keyOutput.getText().concat(btn_x.getText()));
    }//GEN-LAST:event_btn_xActionPerformed

    private void btn_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cActionPerformed
        txf_keyOutput.setText(txf_keyOutput.getText().concat(btn_c.getText()));
    }//GEN-LAST:event_btn_cActionPerformed

    private void btn_vActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_vActionPerformed
        txf_keyOutput.setText(txf_keyOutput.getText().concat(btn_v.getText()));
    }//GEN-LAST:event_btn_vActionPerformed

    private void btn_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bActionPerformed
        txf_keyOutput.setText(txf_keyOutput.getText().concat(btn_b.getText()));
    }//GEN-LAST:event_btn_bActionPerformed

    private void btn_nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nActionPerformed
        txf_keyOutput.setText(txf_keyOutput.getText().concat(btn_n.getText()));
    }//GEN-LAST:event_btn_nActionPerformed

    private void btn_mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mActionPerformed
        txf_keyOutput.setText(txf_keyOutput.getText().concat(btn_m.getText()));
    }//GEN-LAST:event_btn_mActionPerformed

    private void btn_underActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_underActionPerformed
        txf_keyOutput.setText(txf_keyOutput.getText().concat("_"));
    }//GEN-LAST:event_btn_underActionPerformed

    private void btn_dotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dotActionPerformed
        txf_keyOutput.setText(txf_keyOutput.getText().concat("."));
    }//GEN-LAST:event_btn_dotActionPerformed

    private void btn_spaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_spaceActionPerformed
        txf_keyOutput.setText(txf_keyOutput.getText().concat(" "));
    }//GEN-LAST:event_btn_spaceActionPerformed

    private void btn_bckspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bckspaceActionPerformed
        if (!txf_keyOutput.getText().equals("")) {
            txf_keyOutput.setText(txf_keyOutput.getText().substring(0, txf_keyOutput.getText().length() - 1));
        }
    }//GEN-LAST:event_btn_bckspaceActionPerformed

    private void btn_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_okActionPerformed
         Login li = new Login();
         if (isPassword)
         {
             li.txt_pass.setText(output);
         }
         else{
             li.txt_user.setText(output);
         }
         this.dispose();

    }//GEN-LAST:event_btn_okActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        output = "";
        txf_keyOutput.setText("");
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_capsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_capsActionPerformed
        if (caps == false) {
            btn_a.setText("A");
            btn_b.setText("B");
            btn_c.setText("C");
            btn_d.setText("D");
            btn_e.setText("E");
            btn_f.setText("F");
            btn_g.setText("G");
            btn_h.setText("H");
            btn_i.setText("I");
            btn_j.setText("I");
            btn_k.setText("J");
            btn_l.setText("L");
            btn_m.setText("M");
            btn_n.setText("N");
            btn_o.setText("O");
            btn_p.setText("P");
            btn_q.setText("Q");
            btn_r.setText("R");
            btn_s.setText("S");
            btn_t.setText("T");
            btn_u.setText("U");
            btn_v.setText("V");
            btn_w.setText("W");
            btn_x.setText("X");
            btn_y.setText("Y");
            btn_z.setText("Z");
            caps = true;
        } else {
            btn_a.setText("a");
            btn_b.setText("b");
            btn_c.setText("c");
            btn_d.setText("d");
            btn_e.setText("e");
            btn_f.setText("f");
            btn_g.setText("g");
            btn_h.setText("h");
            btn_i.setText("i");
            btn_j.setText("j");
            btn_k.setText("k");
            btn_l.setText("l");
            btn_m.setText("m");
            btn_n.setText("n");
            btn_o.setText("o");
            btn_p.setText("p");
            btn_q.setText("q");
            btn_r.setText("r");
            btn_s.setText("s");
            btn_t.setText("t");
            btn_u.setText("u");
            btn_v.setText("v");
            btn_w.setText("w");
            btn_x.setText("x");
            btn_y.setText("y");
            btn_z.setText("z");
            caps = false;
        }
    }//GEN-LAST:event_btn_capsActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_cancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_a;
    private javax.swing.JButton btn_b;
    private javax.swing.JButton btn_bckspace;
    private javax.swing.JButton btn_c;
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_caps;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_d;
    private javax.swing.JButton btn_dot;
    private javax.swing.JButton btn_e;
    private javax.swing.JButton btn_f;
    private javax.swing.JButton btn_g;
    private javax.swing.JButton btn_h;
    private javax.swing.JButton btn_i;
    private javax.swing.JButton btn_j;
    private javax.swing.JButton btn_k;
    private javax.swing.JButton btn_l;
    private javax.swing.JButton btn_m;
    private javax.swing.JButton btn_n;
    private javax.swing.JButton btn_num;
    private javax.swing.JButton btn_o;
    private javax.swing.JButton btn_ok;
    private javax.swing.JButton btn_p;
    private javax.swing.JButton btn_q;
    private javax.swing.JButton btn_r;
    private javax.swing.JButton btn_s;
    private javax.swing.JButton btn_space;
    private javax.swing.JButton btn_t;
    private javax.swing.JButton btn_u;
    private javax.swing.JButton btn_under;
    private javax.swing.JButton btn_v;
    private javax.swing.JButton btn_w;
    private javax.swing.JButton btn_x;
    private javax.swing.JButton btn_y;
    private javax.swing.JButton btn_z;
    private javax.swing.JPanel pnl_keys;
    private javax.swing.JTextField txf_keyOutput;
    // End of variables declaration//GEN-END:variables
}
